image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - pip3 install docker
          - pip3 install docker-compose
          - docker build -t newman_html_report -f ci/Dockerfile.newman ./ci
          - ls -ll ./ci
          - ls -ll ./ci/newman_mainzelliste_configs
          - cd ci
          - ./executeAllNewmanContainerTests.sh
          - cd ..
          - mkdir -p newman/test-reports/junit/
          - cp -a ci/test_results/. ./newman/test-reports/junit/
          - ls -ll ./ci/test_results/
          - ls -ll ./newman/test-reports/junit/
          - pipe: snyk/snyk-scan:0.2.0
            variables:
              SNYK_TOKEN: "$snyktoken"
              LANGUAGE: "docker"
              IMAGE_NAME: "newman_html_report" # Only required if LANGUAGE set to "docker"
              # PROTECT: "<boolean>" # Optional.
              # DONT_BREAK_BUILD: "<boolean>" # Optional.
              # MONITOR: "<boolean>" # Optional.
              # SEVERITY_THRESHOLD: "<low|medium|high>" # Optional.
              # ORGANIZATION: "<string>" # Optional.
              # PROJECT_FOLDER: "<string>" # Optional.
              # TARGET_FILE: "<string>" # Optional.
              # EXTRA_ARGS: "<string>" # Optional.
              # DEBUG: "<boolean>" # Optional.
        artifacts:
          - ci/test_results/**





options:
  docker: true


    #   - step:
 #       name: docker-compose up and down
 #       script:
 #         - apt-get update
 #         # Add python pip and bash
 #         - apt-get -y install python3-minimal python3-pip
          # Install docker-compose via pip
 #         - pip3 install docker-compose
 #         - docker-compose -f docker-compose.newman.yml up
 #         - docker-compose down
