## This is a basic configuration of mainzelliste inside docker
## Futher information about the image is available inside the docker.md file of this repository
version: "3.1"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=PleasePutASafePasswordHere
  mainzelliste:
    image: mainzelliste
    ports:
      - 8080:8080
    build:
      context: .
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_PASS=PleasePutASafePasswordHere
      - ML_API_KEY=changeThisApiKey
    depends_on:
      - db
