version: "3.1"
services:
  db:
    image: postgres:9.5-alpine
    container_name: mainzelliste_database_container
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=mainzelliste
  mainzelliste:
    image: mainzelliste
    build:
      context: .
    container_name: mainzelliste-container
    secrets:
      - mainzellisteConfig
    environment:
      - ML_CONFIG_FILE=/run/secrets/mainzellisteConfig
    depends_on:
      - db

secrets:
  mainzellisteConfig:
    file: ./config/mainzelliste_docker.conf
