version: "3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=mainzelliste
  mainzelliste:
    build: .
    depends_on:
      - db