version: "3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=mainzelliste
  mainzelliste:
    image: vm-129-150.cloud.dkfz-heidelberg.de/mainzelliste:psd
    depends_on:
      - db